######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

cd "/media/D/BITS_Study/Semester_3/HW-SW_codesign/Project/ADXL/project_1/project_1.srcs/sources_1/edk/system"
if { [xload new system.xmp] != 0 } {
  exit -1
}
xset arch zynq
xset dev xc7z020
xset package clg484
xset speedgrade -1

if { [xset hier sub] != 0 } {
  exit -1
}
xset hdl verilog
save proj
exit
